feat: [SIW-943] Add a dev server component to test integration with the example app
pagopa/io-react-native-integrity pull request #6
Opened 2024-03-14 10:56 UTC by hevelius

### Short description

#### List of Changes

#### How Has This Been Tested?

#### Screenshots (if appropriate):

2024-03-29 14:54 UTC, shadowsheep1 requested changes

2024-03-29 14:54 UTC, shadowsheep1 commented on example/.env.local
> +BACKEND_ADDRESS = ""
Since here we have to put the address along with the schema and port, what about putting a placeholder value or a comment?

```suggestion
# Example BACKEND_ADDRESS = "http://192.168.0.1:3000"
BACKEND_ADDRESS = ""
```

2024-03-29 14:54 UTC, shadowsheep1 commented on backend/README.md
> +$ cp .env.local env.local
This is trivial :)
Anyway, I found that modifying the `.env.local` is enough while building with Xcode. Am I right?

2024-03-29 14:54 UTC, shadowsheep1 commented on example/src/IosApp.tsx
> +      },
I know that it's only a sample app, but what about put together the common code? What do you tink?

2024-03-29 14:54 UTC, shadowsheep1 commented on example/src/IosApp.tsx
> +      }),
This too.

2024-03-29 14:54 UTC, shadowsheep1 commented on example/src/IosApp.tsx
> +      }),
This is backed by the two previous comments.

2024-03-29 15:02 UTC, shadowsheep1 requested changes

2024-03-29 15:02 UTC, shadowsheep1 commented on ios/IoReactNativeIntegrity.swift
> +      let service = DCAppAttestService.shared
Why don't we use a guard like the one above?

2024-03-29 15:02 UTC, shadowsheep1 commented on ios/IoReactNativeIntegrity.swift
> +      let service = DCAppAttestService.shared
As above.

2024-03-29 15:02 UTC, shadowsheep1 commented on ios/IoReactNativeIntegrity.swift
> +      let service = DCAppAttestService.shared
As above

2024-03-29 15:02 UTC, shadowsheep1 commented on ios/IoReactNativeIntegrity.swift
> +  func getAttestation(challenge: String, hardwareKeyTag: String, resolve: @escaping RCTPromiseResolveBlock, reject: @escaping RCTPromiseRejectBlock) -> Void {
When we go over 100/120 characters per line I prefer to put every parameters in its own line. What do you think?

2024-03-29 15:02 UTC, shadowsheep1 commented on ios/IoReactNativeIntegrity.swift
> +  func isAttestationServiceAvailable(resolve: @escaping RCTPromiseResolveBlock, reject: @escaping RCTPromiseRejectBlock) -> Void {
When we go over 100/120 characters per line I prefer to put every parameters in its own line. What do you think?

2024-03-29 15:02 UTC, shadowsheep1 commented on ios/IoReactNativeIntegrity.swift
> +  func generateHardwareKey(resolve: @escaping RCTPromiseResolveBlock, reject: @escaping RCTPromiseRejectBlock) -> Void {
As above.

2024-03-29 15:02 UTC, shadowsheep1 commented on ios/IoReactNativeIntegrity.swift
> +  func generateHardwareSignatureWithAssertion(clientData: String, hardwareKeyTag: String, resolve: @escaping RCTPromiseResolveBlock, reject: @escaping RCTPromiseRejectBlock) -> Void {
As above.

2024-03-29 15:02 UTC, shadowsheep1 commented on ios/IoReactNativeIntegrity.swift
> +        }
I alway suggest to run the code formatter on files before committing. On Xcode the shortcut it `Ctrl+I`.

2024-04-03 13:33 UTC, hevelius commented on ios/IoReactNativeIntegrity.swift
> +      let service = DCAppAttestService.shared
solved [here](https://github.com/pagopa/io-react-native-integrity/pull/6/commits/3e56bc8c6835fdec6b8fe7419f11b24207ddc8ef)

2024-04-03 13:33 UTC, hevelius commented on ios/IoReactNativeIntegrity.swift
> +      let service = DCAppAttestService.shared
solved [here](https://github.com/pagopa/io-react-native-integrity/pull/6/commits/3e56bc8c6835fdec6b8fe7419f11b24207ddc8ef)

2024-04-03 13:33 UTC, hevelius commented on ios/IoReactNativeIntegrity.swift
> +      let service = DCAppAttestService.shared
solved [here](https://github.com/pagopa/io-react-native-integrity/pull/6/commits/3e56bc8c6835fdec6b8fe7419f11b24207ddc8ef)

2024-04-04 07:04 UTC, shadowsheep1 approved these changes
Apart from my latest suggestions, LGTM 👍

2024-04-04 07:04 UTC, shadowsheep1 commented on ios/IoReactNativeIntegrity.swift
> +
```suggestion

```

2024-04-04 07:04 UTC, shadowsheep1 commented on ios/IoReactNativeIntegrity.swift
> +
```suggestion

```

2024-04-04 07:04 UTC, shadowsheep1 commented on ios/IoReactNativeIntegrity.swift
> +
```suggestion

```

2024-04-04 07:04 UTC, shadowsheep1 commented on ios/IoReactNativeIntegrity.swift
> +
```suggestion

```

2024-04-04 07:23 UTC, merged